In [2]:
#%%capture cap 

import sklearn 
import numpy as np
from sklearn.datasets import load_files
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report #7c
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

corpus = load_files('BBC_dataset\BBC', encoding='latin1', load_content=True)
corpus.target_names
X_train, X_test, Y_train, Y_test = train_test_split(corpus.data, corpus.target, test_size=0.2, random_state=None)
#----------------------------------------------------------------------------------------------------------------
#----------------------------------------------------------------------------------------------------------------

vectorizer = CountVectorizer()

matrix1 = vectorizer.fit_transform(X_train)
matrix2 = vectorizer.transform(X_test)

Tokens1 = matrix1.toarray() #transform the training set matrix to an ndarray
Tokens2 = matrix2.toarray()  #transform the test set matrix to array

row_sum1 = np.sum(Tokens1, axis=1) # gets the sum of rows for Tokens1 
row_sum2 = np.sum(Tokens2, axis=1)   #Gets the sum of rows for Tokens2

sumsArray1 = np.zeros(5, dtype = int) # To hold the result for training set 
sumsArray2 = np.zeros(5, dtype = int) # To hold the result for test set

for i in range((len(row_sum1))):
    index = Y_train[i]
    sumsArray1[index] += row_sum1[i]
    
for i in range((len(row_sum2))):
    index = Y_test[i]
    sumsArray2[index] += row_sum2[i]

#print(matrix1.toarray()) #prints non-zero elements

# tokens_array = fitObject.toarray()
# tokens_array2 = fitObject_.toarray()



In [4]:
#FOR Question 7.g
#print(tokens_array)
counter = 0
counter0 = 0
for i,j in np.ndindex(Tokens1.shape):
    counter += 1
    if Tokens1[i,j] == 0:
        counter0 += 1

counter_x = 0
counter_y = 0
counter1_ = 0
counter1 = 0

for i,j in np.ndindex(Tokens1.shape):
    counter_x += 1
    if Tokens1[i,j] == 1:
        counter1_ += 1

for i,j in np.ndindex(Tokens2.shape):
    counter_y += 1
    if Tokens2[i,j] == 1:
        counter1 += 1


In [5]:
mnNB = MultinomialNB() # Instantiating a Multinomial Bayes for the training set
mnNB.fit(matrix1, Y_train)

mnNB_ = MultinomialNB() # Instantiating a Multinomial Bayes for test set(needed for 7.g)
mnNB_.fit(matrix2, Y_test)
    
#My 2 FAV words with their indices: eminem: 4621 ; tennis: 12841 (retrieved by running #print(vectorizer.vocabulary_))

logprob_arr = mnNB.feature_log_prob_
#print(logprob_arr) # displays log(prob) for all features(words)

eminem_arr = logprob_arr[:, 4621] #isolate column 4621 associated with log-prob of eminem and Store it 
tennis_arr = logprob_arr[:, 12841] #isolate column 12841 associated with log-prob of tennis and Store it 

class_prob_eminem = np.zeros(5, dtype = int) # To hold the result for sum of log-probs for each class 
class_prob_tennis = np.zeros(5, dtype = int) # To hold the result for sum of log-probs for each class

for i in range((len(eminem_arr))):
    index = Y_train[i]
    class_prob_eminem[index] += eminem_arr[i]
    
for j in range((len(tennis_arr))):
    index = Y_train[j]
    class_prob_tennis[index] += tennis_arr[j]

classPredict = mnNB.predict(matrix2) #Running classifier on the test set
#--------------------------------------------------------------------------------------------------


In [8]:
# %%capture cap
print('Question 7')
print('MultinomialNB Default values try 1', '\n')
print('(b)')

ConfusionMatrix = metrics.confusion_matrix(Y_test, classPredict)
print('Confusion Matrix: ')
print(ConfusionMatrix, '\n')
print('-------------------------------------------------------------------------------------')

print('(c)')
target_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('\n', 'Classification Report')
print(classification_report(Y_test, classPredict, target_names=target_names))
print('-------------------------------------------------------------------------------------')

print('\n', '(d)')
Accuracy = metrics.accuracy_score(Y_test, classPredict)
MacroF1score = f1_score(Y_test, classPredict, average='macro')
WeightedF1score = f1_score(Y_test, classPredict, average='weighted')
print('Accuracy = ', Accuracy)
print('MacroF1score = ', MacroF1score)
print('WeightedF1score = ', WeightedF1score)
print('-------------------------------------------------------------')
print('(e)')
class_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('Class names: ', class_names)
print('Prior probabilities: ')
prior_log = (mnNB.class_log_prior_)
prior = np.exp(prior_log)
print(prior)
print('-------------------------------------------------------------')

print('(f)')
print('Size of the vocabulary(for training set) is the number of columns: ', matrix1.shape)
print('**Another way to get the size of vocabulary**',mnNB.n_features_in_)  # Also gives the size of vocabulary
print('-------------------------------------------------------------')
print('(g)')
print('Number of word tokens for each class in the training set: ', sumsArray1)
print('Number of word tokens for each class in the test set: ',sumsArray2)  
class_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('Class names: ', class_names)
print('NB: The MultinomialNB attribute class_count_ generates the number of documents for each class which is not what we are looking for!')
print(mnNB.class_count_, 'Number of docs/class for training set')
print(mnNB_.class_count_, 'Number of docs/class for test set')
print(np.add(mnNB.class_count_, mnNB_.class_count_), 'Total number of docs for each class')
print('-------------------------------------------------------------')
print('(h)')
corpusTokens = np.add(sumsArray1, sumsArray2)   
print('Number of tokens in the entire corpus for each class', corpusTokens)
print('Number of tokens in the entire corpus', np.sum(corpusTokens, axis=0))
print('-------------------------------------------------------------')
print('(i)')
print('Number of words with a frequency of zero in trainning set: ', counter0)
print('Percentage of words with a frequency of zero in trainning set:', (counter0/counter)*100, '%')
print('-------------------------------------------------------------')
print('(j)')
print('Number of words with a frequency of one in the entire corpus: ', counter1_ + counter1 )
print('Percentage of words with a frequency of one in the entire corpus:', ((counter1_ + counter1)/(counter_x + counter_y)*100), '%')    
print('-------------------------------------------------------------')
print('(k)')
print('My 2 FAV words with their indices: eminem: 4621 ; tennis: 12841 (retrieved by running vectorizer.vocabulary_)')
print('eminem', 'Log-prob: ', eminem_arr)
print('tennis', 'Log-prob: ', tennis_arr)
print('-------------------------------------------------------------')
# with open('bbc-performance.txt', 'w') as out:
#     out.write(cap.stdout)
#===============================================================================================================

In [9]:
#Step 8, redoing steps 6, 7
mnNB = MultinomialNB() # Instantiating a Multinomial Bayes for the training set
mnNB.fit(matrix1, Y_train)

mnNB_ = MultinomialNB() # Instantiating a Multinomial Bayes for test set(needed for 7.g)
mnNB_.fit(matrix2, Y_test)
    
#My 2 FAV words with their indices: eminem: 4621 ; tennis: 12841 (retrieved by running #print(vectorizer.vocabulary_))

logprob_arr = mnNB.feature_log_prob_
#print(logprob_arr) # displays log(prob) for all features(words)

eminem_arr = logprob_arr[:, 4621] #isolate column 4621 associated with log-prob of eminem and Store it 
tennis_arr = logprob_arr[:, 12841] #isolate column 12841 associated with log-prob of tennis and Store it 

class_prob_eminem = np.zeros(5, dtype = int) # To hold the result for sum of log-probs for each class 
class_prob_tennis = np.zeros(5, dtype = int) # To hold the result for sum of log-probs for each class

for i in range((len(eminem_arr))):
    index = Y_train[i]
    class_prob_eminem[index] += eminem_arr[i]
    
for j in range((len(tennis_arr))):
    index = Y_train[j]
    class_prob_tennis[index] += tennis_arr[j]

classPredict = mnNB.predict(matrix2) #Running classifier on the test set
#--------------------------------------------------------------------------------------------------


In [18]:

print('Question 8')
print('MultinomialNB Default values try 2', '\n')
print('Step 7')
print('(b)')
ConfusionMatrix = metrics.confusion_matrix(Y_test, classPredict)
print('Confusion Matrix: ')
print(ConfusionMatrix, '\n')
print('-------------------------------------------------------------------------------------')
print('(c)')
target_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('\n', 'Classification Report')
print(classification_report(Y_test, classPredict, target_names=target_names))
print('-------------------------------------------------------------------------------------')

print('\n', '(d)')
Accuracy = metrics.accuracy_score(Y_test, classPredict)
MacroF1score = f1_score(Y_test, classPredict, average='macro')
WeightedF1score = f1_score(Y_test, classPredict, average='weighted')

print('Accuracy = ', Accuracy)
print('MacroF1score = ', MacroF1score)
print('WeightedF1score = ', WeightedF1score)
print('-------------------------------------------------------------')

print('(e)')
class_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('Class names: ', class_names)
print('Prior probabilities: ')
prior_log = (mnNB.class_log_prior_)
prior = np.exp(prior_log)
print(prior)
print('-------------------------------------------------------------')

print('(f)')
print('Size of the vocabulary(for training set) is the number of columns: ', matrix1.shape)
print('**Another way to get the size of vocabulary**',mnNB.n_features_in_)  # Also gives the size of vocabulary
print('-------------------------------------------------------------')



Question 8
MultinomialNB Default values try 2 

Step 7
(b)
Confusion Matrix: 
[[87  1  2  0  3]
 [ 0 84  2  0  0]
 [ 0  0 79  0  1]
 [ 0  0  1 96  0]
 [ 1  1  0  0 87]] 

-------------------------------------------------------------------------------------
(c)

 Classification Report
               precision    recall  f1-score   support

     business       0.99      0.94      0.96        93
entertainment       0.98      0.98      0.98        86
     politics       0.94      0.99      0.96        80
        sport       1.00      0.99      0.99        97
         tech       0.96      0.98      0.97        89

     accuracy                           0.97       445
    macro avg       0.97      0.97      0.97       445
 weighted avg       0.97      0.97      0.97       445

-------------------------------------------------------------------------------------

 (d)
Accuracy =  0.9730337078651685
MacroF1score =  0.9725940213120179
WeightedF1score =  0.9730499512552644
---------------------

In [19]:
#%%capture cap
print('(g)')
print('Number of word tokens for each class in the training set: ', sumsArray1)
print('Number of word tokens for each class in the test set: ',sumsArray2)  
class_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('Class names: ', class_names)
print('NB: The MultinomialNB attribute class_count_ generates the number of documents for each class which is not what we are looking for!')
print(mnNB.class_count_, 'Number of docs/class for training set')
print(mnNB_.class_count_, 'Number of docs/class for test set')
print(np.add(mnNB.class_count_, mnNB_.class_count_), 'Total number of docs for each class')
print('-------------------------------------------------------------')
print('(h)')
corpusTokens = np.add(sumsArray1, sumsArray2)   
print('Number of tokens in the entire corpus for each class', corpusTokens)
print('Number of tokens in the entire corpus', np.sum(corpusTokens, axis=0))
print('-------------------------------------------------------------')
print('(i)')
print('Number of words with a frequency of zero in trainning set: ', counter0)
print('Percentage of words with a frequency of zero in trainning set:', (counter0/counter)*100, '%')
print('-------------------------------------------------------------')
print('(j)')
print('Number of words with a frequency of one in the entire corpus: ', counter1_ + counter1 )
print('Percentage of words with a frequency of one in the entire corpus:', ((counter1_ + counter1)/(counter_x + counter_y)*100), '%')    
print('-------------------------------------------------------------')
print('(k)')
print('My 2 FAV words with their indices: eminem: 4621 ; tennis: 12841 (retrieved by running vectorizer.vocabulary_)')
print('eminem', 'Log-prob: ', eminem_arr)
print('tennis', 'Log-prob: ', tennis_arr)
print('-------------------------------------------------------------')
# with open('bbc-performance.txt', 'a') as out:
#     out.write(cap.stdout)


(g)
Number of word tokens for each class in the training set:  [134055  98546 150559 134363 155383]
Number of word tokens for each class in the test set:  [29889 25550 34085 28035 42478]
Class names:  ['business', 'entertainment', 'politics', 'sport', 'tech']
NB: The MultinomialNB attribute class_count_ generates the number of documents for each class which is not what we are looking for!
[417. 300. 337. 414. 312.] Number of docs/class for training set
[93. 86. 80. 97. 89.] Number of docs/class for test set
[510. 386. 417. 511. 401.] Total number of docs for each class
-------------------------------------------------------------
(h)
Number of tokens in the entire corpus for each class [163944 124096 184644 162398 197861]
Number of tokens in the entire corpus 832943
-------------------------------------------------------------
(i)
Number of words with a frequency of zero in trainning set:  47658364
Percentage of words with a frequency of zero in trainning set: 99.24884826983286 %
-----

In [20]:
#STEP 9 with smoothing = 0.0001
mnNB = MultinomialNB(alpha = 0.0001) # Instantiating a Multinomial Bayes for the training set
mnNB.fit(matrix1, Y_train)

mnNB_ = MultinomialNB(alpha = 0.0001) # Instantiating a Multinomial Bayes for test set(needed for 7.g)
mnNB_.fit(matrix2, Y_test)
    
#My 2 FAV words with their indices: eminem: 4621 ; tennis: 12841 (retrieved by running #print(vectorizer.vocabulary_))

logprob_arr = mnNB.feature_log_prob_
#print(logprob_arr) # displays log(prob) for all features(words)

eminem_arr = logprob_arr[:, 4621] #isolate column 4621 associated with log-prob of eminem and Store it 
tennis_arr = logprob_arr[:, 12841] #isolate column 12841 associated with log-prob of tennis and Store it 

class_prob_eminem = np.zeros(5, dtype = int) # To hold the result for sum of log-probs for each class 
class_prob_tennis = np.zeros(5, dtype = int) # To hold the result for sum of log-probs for each class

for i in range((len(eminem_arr))):
    index = Y_train[i]
    class_prob_eminem[index] += eminem_arr[i]
    
for j in range((len(tennis_arr))):
    index = Y_train[j]
    class_prob_tennis[index] += tennis_arr[j]

classPredict = mnNB.predict(matrix2) #Running classifier on the test set
#--------------------------------------------------------------------------------------------------


In [21]:
#%%capture cap
print('Question 9')
print('MultinomialNB try 3 with smoothing value = 0.0001 ', '\n')
print('Step 7')
print('(b)')
ConfusionMatrix = metrics.confusion_matrix(Y_test, classPredict)
print('Confusion Matrix: ')
print(ConfusionMatrix, '\n')
print('-------------------------------------------------------------------------------------')
print('(c)')
target_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('\n', 'Classification Report')
print(classification_report(Y_test, classPredict, target_names=target_names))
print('-------------------------------------------------------------------------------------')

print('\n', '(d)')
Accuracy = metrics.accuracy_score(Y_test, classPredict)
MacroF1score = f1_score(Y_test, classPredict, average='macro')
WeightedF1score = f1_score(Y_test, classPredict, average='weighted')

print('Accuracy = ', Accuracy)
print('MacroF1score = ', MacroF1score)
print('WeightedF1score = ', WeightedF1score)
print('-------------------------------------------------------------')

print('(e)')
class_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('Class names: ', class_names)
print('Prior probabilities: ')
prior_log = (mnNB.class_log_prior_)
prior = np.exp(prior_log)
print(prior)
print('-------------------------------------------------------------')

print('(f)')
print('Size of the vocabulary(for training set) is the number of columns: ', matrix1.shape)
print('**Another way to get the size of vocabulary**',mnNB.n_features_in_)  # Also gives the size of vocabulary
print('-------------------------------------------------------------')

print('(g)')
print('Number of word tokens for each class in the training set: ', sumsArray1)
print('Number of word tokens for each class in the test set: ',sumsArray2)  
class_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('Class names: ', class_names)
print('NB: The MultinomialNB attribute class_count_ generates the number of documents for each class which is not what we are looking for!')
print(mnNB.class_count_, 'Number of docs/class for training set')
print(mnNB_.class_count_, 'Number of docs/class for test set')
print(np.add(mnNB.class_count_, mnNB_.class_count_), 'Total number of docs for each class')
print('-------------------------------------------------------------')
print('(h)')
corpusTokens = np.add(sumsArray1, sumsArray2)   
print('Number of tokens in the entire corpus for each class', corpusTokens)
print('Number of tokens in the entire corpus', np.sum(corpusTokens, axis=0))
print('-------------------------------------------------------------')
print('(i)')
print('Number of words with a frequency of zero in trainning set: ', counter0)
print('Percentage of words with a frequency of zero in trainning set:', (counter0/counter)*100, '%')
print('-------------------------------------------------------------')
print('(j)')
print('Number of words with a frequency of one in the entire corpus: ', counter1_ + counter1 )
print('Percentage of words with a frequency of one in the entire corpus:', ((counter1_ + counter1)/(counter_x + counter_y)*100), '%')    
print('-------------------------------------------------------------')
print('(k)')
print('My 2 FAV words with their indices: eminem: 4621 ; tennis: 12841 (retrieved by running vectorizer.vocabulary_)')
print('eminem', 'Log-prob: ', eminem_arr)
print('tennis', 'Log-prob: ', tennis_arr)
print('-------------------------------------------------------------')
# with open('bbc-performance.txt', 'a') as out:
#     out.write(cap.stdout)


Question 9
MultinomialNB try 3 with smoothing value = 0.0001  

Step 7
(b)
Confusion Matrix: 
[[87  1  2  0  3]
 [ 0 84  2  0  0]
 [ 0  0 79  0  1]
 [ 0  0  1 96  0]
 [ 1  1  0  0 87]] 

-------------------------------------------------------------------------------------
(c)

 Classification Report
               precision    recall  f1-score   support

     business       0.99      0.94      0.96        93
entertainment       0.98      0.98      0.98        86
     politics       0.94      0.99      0.96        80
        sport       1.00      0.99      0.99        97
         tech       0.96      0.98      0.97        89

     accuracy                           0.97       445
    macro avg       0.97      0.97      0.97       445
 weighted avg       0.97      0.97      0.97       445

-------------------------------------------------------------------------------------

 (d)
Accuracy =  0.9730337078651685
MacroF1score =  0.9725940213120179
WeightedF1score =  0.9730499512552644
-----

In [22]:
#STEP 10 with smoothing = 0.9
mnNB = MultinomialNB(alpha = 0.9) # Instantiating a Multinomial Bayes for the training set
mnNB.fit(matrix1, Y_train)

mnNB_ = MultinomialNB(alpha = 0.9) # Instantiating a Multinomial Bayes for test set(needed for 7.g)
mnNB_.fit(matrix2, Y_test)
    
#My 2 FAV words with their indices: eminem: 4621 ; tennis: 12841 (retrieved by running #print(vectorizer.vocabulary_))

logprob_arr = mnNB.feature_log_prob_
#print(logprob_arr) # displays log(prob) for all features(words)

eminem_arr = logprob_arr[:, 4621] #isolate column 4621 associated with log-prob of eminem and Store it 
tennis_arr = logprob_arr[:, 12841] #isolate column 12841 associated with log-prob of tennis and Store it 

class_prob_eminem = np.zeros(5, dtype = int) # To hold the result for sum of log-probs for each class 
class_prob_tennis = np.zeros(5, dtype = int) # To hold the result for sum of log-probs for each class

for i in range((len(eminem_arr))):
    index = Y_train[i]
    class_prob_eminem[index] += eminem_arr[i]
    
for j in range((len(tennis_arr))):
    index = Y_train[j]
    class_prob_tennis[index] += tennis_arr[j]

classPredict = mnNB.predict(matrix2) #Running classifier on the test set
#--------------------------------------------------------------------------------------------------


In [23]:
print('Question 10')
print('MultinomialNB try 4 with smoothing value = 0.9 ', '\n')
print('Step 7')
print('(b)')
ConfusionMatrix = metrics.confusion_matrix(Y_test, classPredict)
print('Confusion Matrix: ')
print(ConfusionMatrix, '\n')
print('-------------------------------------------------------------------------------------')
print('(c)')
target_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('\n', 'Classification Report')
print(classification_report(Y_test, classPredict, target_names=target_names))
print('-------------------------------------------------------------------------------------')

print('\n', '(d)')
Accuracy = metrics.accuracy_score(Y_test, classPredict)
MacroF1score = f1_score(Y_test, classPredict, average='macro')
WeightedF1score = f1_score(Y_test, classPredict, average='weighted')

print('Accuracy = ', Accuracy)
print('MacroF1score = ', MacroF1score)
print('WeightedF1score = ', WeightedF1score)
print('-------------------------------------------------------------')

print('(e)')
class_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('Class names: ', class_names)
print('Prior probabilities: ')
prior_log = (mnNB.class_log_prior_)
prior = np.exp(prior_log)
print(prior)
print('-------------------------------------------------------------')

print('(f)')
print('Size of the vocabulary(for training set) is the number of columns: ', matrix1.shape)
print('**Another way to get the size of vocabulary**',mnNB.n_features_in_)  # Also gives the size of vocabulary
print('-------------------------------------------------------------')

print('(g)')
print('Number of word tokens for each class in the training set: ', sumsArray1)
print('Number of word tokens for each class in the test set: ',sumsArray2)  
class_names = ['business', 'entertainment', 'politics', 'sport', 'tech']
print('Class names: ', class_names)
print('NB: The MultinomialNB attribute class_count_ generates the number of documents for each class which is not what we are looking for!')
print(mnNB.class_count_, 'Number of docs/class for training set')
print(mnNB_.class_count_, 'Number of docs/class for test set')
print(np.add(mnNB.class_count_, mnNB_.class_count_), 'Total number of docs for each class')
print('-------------------------------------------------------------')
print('(h)')
corpusTokens = np.add(sumsArray1, sumsArray2)   
print('Number of tokens in the entire corpus for each class', corpusTokens)
print('Number of tokens in the entire corpus', np.sum(corpusTokens, axis=0))
print('-------------------------------------------------------------')
print('(i)')
print('Number of words with a frequency of zero in trainning set: ', counter0)
print('Percentage of words with a frequency of zero in trainning set:', (counter0/counter)*100, '%')
print('-------------------------------------------------------------')
print('(j)')
print('Number of words with a frequency of one in the entire corpus: ', counter1_ + counter1 )
print('Percentage of words with a frequency of one in the entire corpus:', ((counter1_ + counter1)/(counter_x + counter_y)*100), '%')    
print('-------------------------------------------------------------')
print('(k)')
print('My 2 FAV words with their indices: eminem: 4621 ; tennis: 12841 (retrieved by running vectorizer.vocabulary_)')
print('eminem', 'Log-prob: ', eminem_arr)
print('tennis', 'Log-prob: ', tennis_arr)
print('-------------------------------------------------------------')
# with open('bbc-performance.txt', 'a') as out:
#     out.write(cap.stdout)


Question 10
MultinomialNB try 4 with smoothing value = 0.9  

Step 7
(b)
Confusion Matrix: 
[[89  0  2  0  2]
 [ 0 84  1  0  1]
 [ 1  0 78  0  1]
 [ 0  0  1 96  0]
 [ 0  1  0  0 88]] 

-------------------------------------------------------------------------------------
(c)

 Classification Report
               precision    recall  f1-score   support

     business       0.99      0.96      0.97        93
entertainment       0.99      0.98      0.98        86
     politics       0.95      0.97      0.96        80
        sport       1.00      0.99      0.99        97
         tech       0.96      0.99      0.97        89

     accuracy                           0.98       445
    macro avg       0.98      0.98      0.98       445
 weighted avg       0.98      0.98      0.98       445

-------------------------------------------------------------------------------------

 (d)
Accuracy =  0.9775280898876404
MacroF1score =  0.9770582084799463
WeightedF1score =  0.9775868029015019
-------